version: "3"
services:
  postgres-app-cliente:
    image: postgres:latest
    environment:
      POSTGRES_DB: cadastro_cliente
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  spring-app-cliente:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres-app-cliente